name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Developer Command Prompt for Microsoft Visual C++
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Install FFmpeg
      shell: bash
      run: |
        FILENAME="ffmpeg-n4.4-latest-win32-gpl-shared-4.4"
        curl -fLOSs https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/download/latest/$FILENAME.zip
        7z x $FILENAME.zip
        $FILENAME >> $GITHUB_PATH

    - name: Build
      shell: bash
      run: |
        cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Deploy
      shell: bash
      run: |
        mkdir deploy
        cp *.exe deploy
        cp *.dll deploy
        cd deploy
        windeployqt si-edit.exe libweaver.dll
        7z a libweaver.zip *

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path:
          deploy/libweaver.7z

    - name: Upload to Releases
      shell: bash
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TRAVIS_REPO_SLUG: itsmattkc/libweaver
        TRAVIS_COMMIT: ${{ github.sha }}
      run: |
        curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
        ./upload.sh deploy/libweaver.7z
